### ISSUE TITLE
Please upgrade to a newer version of NPM

### ISSUE THREAD

**Issue by fmal** [Blacklite/Ncapsulate#14]
Current version ships with older NPM, which doesn't support per-project npmrc files. At least 1.4.21 is needed.

Thanks

**Comment by vossad01** [comment]
This issue was closed, but it does not look like an upgrade happened.  Do I have this right?

**Comment by david-driscoll** [comment]
I didn't close it myself, I just hadn't had the time.   I've added an appveyor config, and now the builds will auto-promote to Nuget.

**Comment by adamvoss** [comment]
I was dealing with [race conditions in npm](https://github.com/npm/npm/issues/5857).  Finally had to require installing node locally on all boxes to get a fixed version for NCapsulate to use.
